version: '3'

services:

# CONTAINER DO BANCO DE DADOS
  loteriapgsql:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'loteriapgsql'
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword

# CONTAINER DO SISTEMA GERENCIADOR DE BANCO DE DADOS (SGBD)
  adminer:
    image: adminer
    ports:
      - 8080:8080

  app:
    container_name: loteria
    restart: always
    build: .
    ports:
        - "3333:3333"
    depends_on:
        - loteriapgsql

volumes:
  pg-data:
